FROM python:3.12.12-slim
WORKDIR app/
COPY info/requirements.txt app/info/requirements.txt

RUN pip3 install  --no-cache

Flask==3.0.3
Werkzeug==3.0.4
Jinja2==3.1.4
itsdangerous==2.2.0
click==8.1.7
waitress==3.0.0
